<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="hostdbmgd">
      <HintPath>..\..\..\..\Desktop\nCAD_SDK\include-x64\hostdbmgd.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="hostmgd">
      <HintPath>..\..\..\..\Desktop\nCAD_SDK\include-x64\hostmgd.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="ncBIMSmgd">
      <HintPath>..\..\..\..\Desktop\nBIM_SDK\include-x64\ncBIMSmgd.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="NrxGateMgd">
      <HintPath>..\..\..\..\Desktop\nCAD_SDK\include-x64\nrxgatemgd.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

</Project>
